# Eggs.Variant
#
# Copyright Agustin K-ballo Berge, Fusion Fenix 2014-2017
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

platform: x64

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

branches:
  only:
    - master
    - develop
    - explicit

init:
  - ps: >-
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2013") {
        $env:GENERATOR="Visual Studio 12 2013"
      } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {
        $env:GENERATOR="Visual Studio 14 2015"
      } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {
        $env:GENERATOR="Visual Studio 15 2017"
      }

build_script:
  - mkdir build
  - cd build
  - echo cmake -G "%GENERATOR%" -A x64
  - cmake -G "%GENERATOR%" -A x64 ..
  - echo cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION%
  - echo ctest -V --build-config %CONFIGURATION%
  - ctest -V --build-config %CONFIGURATION%
